module GameData
  NORMAL_RANK_CONTEST_POKEMON = {
    "Beauty" => [:SLAKOTH, :BEAUTIFLY, :ELECTRIKE, :DUSTOX, :TAILLOW, :WINGULL, :ZUBAT, :CORPHISH, :LOTAD, :SILCOON, :COTTONNEE, ],
    "Cute" => [:HOPPIP, :SLAKOTH, :ZIGZAGOON, :LEDYBA, :POLIWAG, :WINGULL, :GULPIN, :ZUBAT, :WHISMUR, :MINUN, :PLUSLE, :EEVEE, :MARILL, :PICHU, :PARAS, ],
    "Tough" => [:SLAKOTH, :POLIWAG, :DIGLETT, :TOTODILE, :POOCHYENA, :SEEDOT, :DELIBIRD, :GEODUDE, :MAKUHITA, :ARON, :MAGIKARP, :MARILL, :CACNEA],
    "Smart" => [:BULBASAUR, :BUTTERFREE, :DIGLETT, :SHROOMISH, :SEEDOT , :NINCADA, :ZUBAT, :WHISMUR , :RALTS, :PICHU,:PHANTUMP, :ZORUA,],
    "Cool" => [:ELECTRIKE, :CASCOON, :DUSTOX, :POOCHYENA, :PIDGEOTTO, :LEDYBA, :TAILLOW, :ARON, :MAKUHITA, :TENTACOOL, :DUSTOX, :PARAS, :SPEAROW],
  }

  SUPER_RANK_CONTEST_POKEMON = {
    "Beauty" => [:BLISSEY, :GOLDEEN, :SWABLU, :LINOONE, :DODUO, :SKARMORY, :SEEL, :ROSELIA, :LOTAD, :BALTOY, :NUMEL, :MISDREAVUS, :DROWZEE, :ROSELIA, :DODUO, :LINOONE, :KECLEON, :BARBOACH, :SWABLU, :SPOINK, :NUMEL],
    "Cute" => [:BLISSEY, :LINOONE, :DODUO, :SEEL, :LOTAD, :SLOWBRO, :SPINDA, :ELEKID, :FARFETCHD, :BARBOACH, :DROWZEE, :ROSELIA, :BARBOACH, :SWABLU, :SPOINK, :SPINDA],
    "Tough" => [:BLISSEY, :DODUO, :SKARMORY, :SANDSHREW, :TRAPINCH, :SNUBULL, :HITMONCHAN, :BARBOACH, :NUMEL, :DROWZEE, :DODUO, :LINOONE, :KECLEON, :CORPHISH, :TRAPINCH],
    "Smart" => [:KECLEON, :SWABLU, :LOTAD, :SLOWBRO, :SPINDA, :BALTOY, :MISDREAVUS, :CACNEA, :BARBOACH, :DROWZEE, :CACNEA, :BALTOY, :SPINDA, :LOTAD, :MACHOKE],
    "Cool" => [:GOLDEEN, :DODUO, :SKARMORY, :SANDSHREW, :HITMONCHAN, :ELEKID, :FARFETCHD, :NUMEL, :CACNEA, :SANDSHREW, :DODUO, :LINOONE, :KECLEON, :MACHOKE, :PIKACHU],
  }

  HYPER_RANK_CONTEST_POKEMON = {
    "Beauty" => [:BEAUTIFLY, :PINECO, :SHIFTRY, :ABSOL, :MILTANK, :HOUNDOOM, :LOMBRE, :LUNATONE, :WAILMER, :BEAUTIFLY, :NUZLEAF, :SEAKING, :CAMERUPT, :MACHOKE],
    "Cute" => [:CUBONE, :MILTANK, :NINJASK, :DUNSPARCE, :SQUIRTLE, :MAGIKARP, :LOMBRE, :KANGASKHAN, :WAILMER, :LOMBRE, :WAILMER, :MAGIKARP, :MACHOKE, :CAMERUPT],
    "Tough" => [:CUBONE, :HITMONLEE, :MACHOKE, :CASTFORM, :MIGHTYENA, :EXEGGUTOR, :DUNSPARCE, :KANGASKHAN, :LAIRON, :MAGIKARP, :LAIRON, :NINJASK, :SEVIPER, :MACHOP],
    "Smart" => [:BEAUTIFLY, :PINECO, :NINJASK, :CASTFORM, :MIGHTYENA, :EXEGGUTOR, :SEVIPER, :LUNATONE, :LAIRON, :SEAKING, :LAIRON, :MIGHTYENA, :BEAUTIFLY, :SEVIPER, :LOMBRE, :LUNATONE, :ADDISON],
    "Cool" => [:SHIFTRY, :ABSOL, :HITMONLEE, :MACHOKE, :CASTFORM, :HOUNDOOM, :KANGASKHAN, :SWELLOW, :NUZLEAF, :SWELLOW, :SEAKING, :MACHOP, :PELIPPER],
  }

  MASTER_RANK_CONTEST_POKEMON = {
    "Beauty" => [:ALTARIA, :MILOTIC, :BELLOSSOM, :WOBBUFFET, :ESPEON, :GYARADOS, :JYNX, :ELECTRODE, :DELCATTY, :GOREBYSS, :VILEPLUME, :WOBBUFFET],
    "Cute" => [:ALTARIA, :BELLOSSOM, :TOGETIC, :CHANSEY, :PICHU, :XATU, :SLAKING, :LUVDISC, :MEOWTH, :SABLEYE, :DELCATTY, :SLOWKING, :PORYGON, :DELCATTY, :SLAKING, :LUVDISC, :PICHU, :ESPEON , :ILLUMISE],
    "Tough" => [:ALTARIA, :SHARPEDO, :HERACROSS, :WOBBUFFET, :GYARADOS, :XATU, :SLAKING, :LUVDISC, :URSARING, :DRAGONITE, :SLOWKING, :GYARADOS, :SLAKING, :HERACROSS, :SHARPEDO, :DUSCLOPS, :MACHAMP],
    "Smart" => [:ALTARIA, :BELLOSSOM, :XATU, :WOBBUFFET, :MEOWTH, :SABLEYE, :KIRLIA, :JYNX, :PORYGON, :KIRLIA, :DUSCLOPS, :ILLUMISE, :LUVDISC, :SHARPEDO],
    "Cool" => [:ALTARIA, :SHARPEDO, :HERACROSS, :WOBBUFFET, :UMBREON, :GYARADOS, :URSARING, :DRAGONITE, :ELECTRODE, :KIRLIA, :LOUDRED, :PORYGON, :GYARADOS, :LOUDRED, :ELECTRODE, :HERACROSS],
  }
end
