class Scene_Credits
  CREDIT_HOENN = <<_END_

<title>Pokémon Infinite Fusion 2: Hoenn
<title>PART 1
By Chardub (Frogzilla)

<title>Game design
Chardub<s>Payapon

<title>Programming:
Chardub

<title>Autogenerated Sprites :
Japeal - Pokefusion 2
http://japeal.com/pkm

Special thanks to Aegide and Reizod for 
helping to download the autogenerated sprites 
and to the owners of Japeal for accepting to 
share their sprites.

<title>Maps
Chardub<s>Payapon
Kiwikelly<s>

<title>Gameplay / Story
Chardub<s>Payapon

<title>Title screen and logo
Doctor Miawoo

<title>Intro animation:
Kiwikelly

<title>Music:
Pory

<title>Game Assets Management
Payapon

<title>Custom sprites collecting and handling
Payapon

With contributions and tools by:
Kiwikelly, Greystorm, Sapphire_chuu

<title>Trainer Teams and dialogs:
.realthree<s>chardub
funkytomate<s>kiwikelly
pory<s>shiro0170
gordogamr<s>theheroicorange

<title>Overworld Pokémon Sprites:
milchik<s>.payapon
gordogamr<s>.realthree
chardub<s>

<title>Battle Backgrounds Coordination:
.realthree<s>piponus

<title>Battle Backgrounds Art:
.realthree<s>koalagators
piponus<s>aplastic
cynder_<s>chansondoree
kiwikelly<s>revellr
slowforest<s>takopus

<title>QA Testing (Part 1)
adonis9410<s>casinosluck
firesword2562<s>divinelunaria
sapphire_chuu<s>vampvixen

<title>Character Customization graphics coordination:
Chardub
Gummy.Frog
Payapon

<title>Discord custom sprites coordination:
CaBiNE<s>hero.drawing
Howls<s>Milchik
Payapon<s>

<title>Pokedex entries coordination:
.izik<s>.realthree

<title>Pokedex entries quality control
dragon_hunter_70<s>.izik
knilk<s>lordjoostmeister
quackquackattack<s>.realthree
eiskitsune<s>wildheartrazorfangs
ziggaway<s>

Pokédex entries were submitted by the community
The individual credits are displayed in-game

<title>Custom Sprites
All of the custom fused Pokémon sprites 
were made by various members of the
Pokémon Infinite Fusion Discord
The individual credits are displayed in-game

It includes significant contributions from:

{SPRITER_CREDITS}

<title>Character Customization Graphics
<title>(Top Contributors)
{CC_CREDITS}

<title>Other custom graphics:
Kiwikelly<s>Payapon
Knucklese<s>UnworthyPie
Doctor Miawoo<s>TCGrunler#4583
Chardub<s>


The following free resources were also used 
with their respective authors' consent:

<title>Trainer Overworld and Battle sprites
Pokémon Destination Project
Adapted by Payapon

<title>Pokémon Overworld sprites
Dewitty<s>Chocosrawloid
Kymontonian<s>milomilotic11
Neo-Spriteman<s>hamsterskull
Sparta<s>pokewiki.de 

<title>Public use tileset graphics:
Alucus BoOmxBiG<s>chimcharsfireworkd
EpicDay<s>EternalTakai
Gallanty Heavy-Metal-Lover<s>Hek-el-grande
DirtyWiggles<s>iametrine
Jorginho<s>kizemaru-kurunosuke
KKKaito<s>kyle-dove
Minorthreat0987<s>Phyromatical
Pokemon-Diamond<s>rayd12smitty
Rossay<s>Shiney570
Spacemotion<s>Speedialga
ThatsSoWitty Thurpok<s>TyranitarDark
UltimoSpriter<s>WesleyFG

{INSERTS_PLUGIN_CREDITS_DO_NOT_REMOVE}

<title>Pokémon Contests & Berry Dex script
wrigty12<s>bo4p5687
Marin<s>mej71
Maruno<s>FL
JV<s>Umbreon/Hansiec
Radical Raptr<s>FL
Luka S.J.<s>TastyRedTomato
Adapted by Chardub

<title>"Pokémon Essentials" was created by:
Flameguru
Poccil (Peter O.)
Maruno

With contributions from:
AvatarMonkeyKirby<s>MiDas Mike
Boushy<s>Near Fantastica
Brother1440<s>PinkMan
FL.<s>Popper
Genzai Kawakami<s>Rataime
Harshboy<s>SoundSpawn
help-14<s>the__end
IceGod64<s>Venom12
Jacob O. Wobbrock<s>Wachunga
KitsuneKouta<s>xLeD
Lisa Anthony<s>
and everyone else who helped out

<title>"mkxp-z" by:
Roza
Based on MKXP by Ancurio et al.

<title>"RPG Maker XP" by:
Enterbrain

This game was inspired by the original
fusion generator: 
alexonsager.alexonsager.net

All generated fusion sprites in this game
come from the Pokémon Fusion Generator:
https://japeal.com/pkm/

Pokémon is owned by:
The Pokémon Company
Nintendo
Affiliated with Game Freak


<title>Thank for playing!
<title>We hope you're looking forward to the full game!


<title>This is a non-profit fan-made game.
<title>No copyright infringements intended.
_END_
end
