class Scene_Credits
  CREDIT_KANTO = <<_END_

<title>Pokémon Infinite Fusion
<title>By Chardub (Frogzilla)

<title>Programming / Game design:
Chardub

<title>Fused Pokemon Sprites :
Japeal - Pokefusion 2
http://japeal.com/pkm

Special thanks to Aegide and Reizod for 
helping to download the autogenerated sprites 
and to the owners of Japeal for accepting to 
share their sprites.

<title>Maps:
Chardub
Kiwikelly
Some of the maps were based on work by:
BenGames, Zeak6464

<title>Gameplay / Story :
Chardub
Kiwikelly

<title>Title screen and logo
Doctor Miawoo

<title>Intro animation:
Kiwikelly

<Music>
mystora (Team Rocket Saffron City)

<title>Custom sprites collecting and handling
Kiwikelly, Payapon, Thornsoflight, Greystorm


<title>Discord custom sprites coordination
avianAnnihilator<s>Blaquaza
BéBoutton<s>CaBiNE
CoramSun<s>hero.drawing
Howls<s>Ignus
Kiwi<s>Maelmc
Milchik the Miltank<s>Payapon
Pix<s>Rosemagwin
Thornsoflight

All of the custom fused Pokémon sprites 
were made by various members of the
Pokémon Infinite Fusion Discord

Including significant contributions from:

{SPRITER_CREDITS}

<title>Character Customization Graphics
(Top Contributors)
{CC_CREDITS}

<title>Other custom graphics:
Kiwikelly<s>Knuckles
UnworthyPie<s>Doctor Miawoo
Chardub<s>TCGrunler#4583

<title>Elite 4 rematch teams
duskrd<s>anaconja
taraline<s>

<title>French translation
anthonygourmand
locpic_
blood.wolf58 (Willi)
ragzzh

<title>The following free resources were also used 
<title>with their respective authors' consent:

<title>Public use tileset graphics:
Alucus BoOmxBiG<s>chimcharsfireworkd
EpicDay<s>EternalTakai
Gallanty Heavy-Metal-Lover<s>Hek-el-grande
DirtyWiggles<s>iametrine
Jorginho<s>kizemaru-kurunosuke
KKKaito<s>kyle-dove
Minorthreat0987<s>Phyromatical
Pokemon-Diamond<s>rayd12smitty
Rossay<s>Shiney570
Spacemotion<s>Speedialga
ThatsSoWitty Thurpok<s>TyranitarDark
UltimoSpriter<s>WesleyFG

<title>Public use music:    
Pokeli, TailDoll666100
Kazune Sawatari, sentsinkantéun,
Nanashima, CharizardTheMaster, The Zame Jack 

{INSERTS_PLUGIN_CREDITS_DO_NOT_REMOVE}

<title>"Pokémon Essentials" was created by:
Flameguru
Poccil (Peter O.)
Maruno

With contributions from:
AvatarMonkeyKirby<s>MiDas Mike
Boushy<s>Near Fantastica
Brother1440<s>PinkMan
FL.<s>Popper
Genzai Kawakami<s>Rataime
Harshboy<s>SoundSpawn
help-14<s>the__end
IceGod64<s>Venom12
Jacob O. Wobbrock<s>Wachunga
KitsuneKouta<s>xLeD
Lisa Anthony<s>
and everyone else who helped out

<title>"mkxp-z" by:
Roza
Based on MKXP by Ancurio et al.

<title>"RPG Maker XP" by:
Enterbrain

<title>This game was inspired by the original
<title>fusion generator: 
alexonsager.alexonsager.net

<title>All generated fusion sprites in this game
<title>come from the Pokémon Fusion Generator:
https://japeal.com/pkm/

<title>Pokémon is owned by:
The Pokémon Company
Nintendo
Affiliated with Game Freak

<title>This is a non-profit fan-made game.
<title>No copyright infringements intended.
_END_
end
