class Scene_Credits
  CREDIT_KANTO = <<_END_

Pokémon Infinite Fusion
By Chardub (Frogzilla)

Programming / Game design:
Chardub

Fused Pokemon Sprites :
Japeal - Pokefusion 2
http://japeal.com/pkm

Special thanks to Aegide and Reizod for 
helping to download the autogenerated sprites 
and to the owners of Japeal for accepting to 
share their sprites.

Maps:
Chardub
Kiwikelly
Some of the maps were based on work by:
BenGames, Zeak6464

Gameplay / Story :
Chardub
Kiwikelly

Title screen and logo
Doctor Miawoo

Intro animation:
Kiwikelly

Custom sprites collecting and handling
Kiwikelly, Payapon, Thornsoflight, Greystorm

Hoenn Trainer teams and dialogs: 
.Realthree
Chardub
Funkytomate
Kiwikelly
Pory
Shiro0170
Gordogamr
Theheroicorange



Discord custom sprites coordination
avianAnnihilator<s>Blaquaza
BéBoutton<s>CaBiNE
CoramSun<s>hero.drawing
Howls<s>Ignus
Kiwi<s>Maelmc
Milchik the Miltank<s>Payapon
Pix<s>Rosemagwin
Thornsoflight

All of the custom fused Pokémon sprites 
were made by various members of the
Pokémon Infinite Fusion Discord

Including significant contributions from:

{SPRITER_CREDITS}

Other custom graphics:
Kiwikelly<s>Knuckles
UnworthyPie<s>Doctor Miawoo
Chardub<s>TCGrunler#4583

Elite 4 rematch teams
duskrd<s>anaconja<s>taraline

French translation
anthonygourmand
locpic_
blood.wolf58 (Willi)
ragzzh

The following free resources were also used 
with their respective authors' consent:

Public use tileset graphics:
Alucus BoOmxBiG<s>chimcharsfireworkd
EpicDay<s>EternalTakai
Gallanty Heavy-Metal-Lover<s>Hek-el-grande
DirtyWiggles<s>iametrine
Jorginho<s>kizemaru-kurunosuke
KKKaito<s>kyle-dove
Minorthreat0987<s>Phyromatical
Pokemon-Diamond<s>rayd12smitty
Rossay<s>Shiney570
Spacemotion<s>Speedialga
ThatsSoWitty Thurpok<s>TyranitarDark
UltimoSpriter<s>WesleyFG

Public use music:    
Pokeli, TailDoll666100
Kazune Sawatari, sentsinkantéun,
Nanashima, CharizardTheMaster, The Zame Jack 

{INSERTS_PLUGIN_CREDITS_DO_NOT_REMOVE}

"Pokémon Essentials" was created by:
Flameguru
Poccil (Peter O.)
Maruno

With contributions from:
AvatarMonkeyKirby<s>MiDas Mike
Boushy<s>Near Fantastica
Brother1440<s>PinkMan
FL.<s>Popper
Genzai Kawakami<s>Rataime
Harshboy<s>SoundSpawn
help-14<s>the__end
IceGod64<s>Venom12
Jacob O. Wobbrock<s>Wachunga
KitsuneKouta<s>xLeD
Lisa Anthony<s>
and everyone else who helped out

"mkxp-z" by:
Roza
Based on MKXP by Ancurio et al.

"RPG Maker XP" by:
Enterbrain

This game was inspired by the original
fusion generator: 
alexonsager.alexonsager.net

All generated fusion sprites in this game
come from the Pokémon Fusion Generator:
https://japeal.com/pkm/

Pokémon is owned by:
The Pokémon Company
Nintendo
Affiliated with Game Freak

This is a non-profit fan-made game.
No copyright infringements intended.
_END_
end
