class BattledTrainer
  TRAINER_CLASS_FAVORITE_TYPES =
    {
      RIVAL1: [:ANY],
      RIVAL2: [:ANY],
      AROMALADY:      [:GRASS, :FAIRY],
      BEAUTY:         [:FAIRY, :WATER, :NORMAL, :GRASS],
      BIKER:          [:POISON, :DARK],
      BIRDKEEPER:     [:FLYING],
      BUGCATCHER:     [:BUG],
      BURGLAR:        [:FIRE, :DARK],
      CHANNELER:      [:GHOST, :PSYCHIC],
      CUEBALL:        [:FIGHTING, :STEEL],
      ENGINEER:       [:ELECTRIC, :STEEL],
      FISHERMAN:      [:WATER],
      GAMBLER:        [:NORMAL, :PSYCHIC],
      GENTLEMAN:      [:NORMAL, :STEEL],
      HIKER:          [:ROCK, :GROUND],
      JUGGLER:        [:PSYCHIC, :GHOST, :NORMAL, :POISON],
      LADY:           [:FAIRY, :NORMAL],
      PAINTER:        [:NORMAL, :PSYCHIC, :GRASS],
      POKEMANIAC:     [:DRAGON, :GROUND],
      POKEMONBREEDER: [:NORMAL, :GRASS],
      PROFESSOR:      [:NORMAL, :PSYCHIC],
      ROCKER:         [:ELECTRIC, :FIRE],
      RUINMANIAC:     [:GROUND, :ROCK, :PSYCHIC],
      SAILOR:         [:WATER, :FIGHTING],
      SCIENTIST:      [:ELECTRIC, :STEEL, :POISON],
      SUPERNERD:      [:ELECTRIC, :PSYCHIC, :STEEL],
      TAMER:          [:NORMAL, :DARK],
      BLACKBELT:      [:FIGHTING],
      CRUSHGIRL:      [:FIGHTING],
      CAMPER:         [:BUG, :NORMAL, :GRASS],
      PICNICKER:      [:GRASS, :NORMAL],
      COOLTRAINER_M:  [:DRAGON, :STEEL, :FIRE],
      COOLTRAINER_F:  [:ICE, :PSYCHIC, :FAIRY],
      YOUNGSTER:      [:NORMAL, :BUG, :GRASS, :FLYING],
      LASS:           [:NORMAL, :FAIRY],
      POKEMONRANGER_M: [:GRASS, :GROUND],
      POKEMONRANGER_F: [:GRASS, :WATER],
      PSYCHIC_M:      [:PSYCHIC, :GHOST],
      PSYCHIC_F:      [:PSYCHIC, :FAIRY],
      SWIMMER_M:      [:WATER, :ICE],
      SWIMMER_F:      [:WATER, :ICE],
      SWIMMER2_M:     [:WATER],
      SWIMMER2_F:     [:WATER],
      TUBER_M:        [:WATER],
      TUBER_F:        [:WATER],
      TUBER2_M:       [:WATER],
      TUBER2_F:       [:WATER],
      COOLCOUPLE:     [:FIRE, :ICE],
      CRUSHKIN:       [:FIGHTING],
      SISANDBRO:      [:WATER, :GROUND],
      TWINS:          [:FAIRY, :NORMAL],
      YOUNGCOUPLE:    [:NORMAL, :PSYCHIC],
      SOCIALITE:      [:FAIRY, :NORMAL],
      BUGCATCHER_F:   [:BUG],
      ROUGHNECK:      [:DARK, :FIGHTING],
      TEACHER:        [:PSYCHIC, :NORMAL],
      PRESCHOOLER_M:  [:NORMAL, :BUG],
      PRESCHOOLER_F:  [:FAIRY, :NORMAL],
      HAUNTEDGIRL_YOUNG:  [:GHOST],
      HAUNTEDGIRL:        [:GHOST, :DARK],
      CLOWN:          [:PSYCHIC, :FAIRY],
      NURSE:          [:NORMAL, :FAIRY],
      WORKER:         [:STEEL, :GROUND],
      COOLTRAINER_M2: [:FIGHTING, :STEEL],
      COOLTRAINER_F2: [:PSYCHIC, :ICE],
      FARMER:         [:GRASS, :GROUND, :NORMAL],
      PYROMANIAC:     [:FIRE],
      KIMONOGIRL:     [:FAIRY, :PSYCHIC, :GHOST],
      SAGE:           [:PSYCHIC, :GHOST],
      PLAYER:         [:ICE, :FIGHTING],
      POLICE:         [:DARK, :FIGHTING],
      SKIER_F:        [:ICE],
      DELIVERYMAN:  [:NORMAL],

      SCHOOLBOY:  [:BUG, :NORMAL, :GRASS],
      SCHOOLGIRL:  [:BUG, :NORMAL , :GRASS],
      TWIN_1:          [:FAIRY, :NORMAL],
      TWIN_2:          [:FAIRY, :NORMAL],
      POKEFAN_M:          [:WATER, :FIRE, :GRASS, :ELECTRIC],
      POKEFAN_F:          [:WATER, :FIRE, :GRASS, :ELECTRIC],
      RICHBOY:          [:NORMAL, :GRASS],
      POKEMONBREEDER_M:          [:NORMAL, :GRASS],
      STREETTHUG:          [:POISON, :DARK, :FIGHTING],
      DELINQUENT:          [:POISON, :DARK, :FIGHTING],
      BUGMANIAC:          [:BUG],
      EXPERT_M:          [:FIGHTING],
      EXPERT_F:          [:FIGHTING],
      COLLECTOR:          [:ROCK, :STEEL, :DRAGON, :FAIRY, :GHOST, :PSYCHIC],
      SURFER:          [:WATER, :FLYING],
      DIVER_M:          [:WATER],
      DIVER_F:          [:WATER],
      REPORTER:          [:NORMAL],
      CAMERAMAN:          [:ELECTRIC],
      NINJABOY:          [:BUG, :POISON],
      DRAGONTAMER:          [:DRAGON],
      TRIATHLETE_BIKE_M:          [:GROUND,:WATER, :FLYING],
      TRIATHLETE_BIKE_F:          [:GROUND,:WATER, :FLYING],
      TRIATHLETE_SWIM_M:          [:GROUND,:WATER, :FLYING],
      TRIATHLETE_SWIM_F:          [:GROUND,:WATER, :FLYING],
      TRIATHLETE_RUN_M:          [:GROUND,:WATER, :FLYING],
      TRIATHLETE_RUN_F:          [:GROUND,:WATER, :FLYING],
      YOUNGCOUPLE_M:          [:NORMAL, :PSYCHIC],
      YOUNGCOUPLE_F:          [:NORMAL, :PSYCHIC],
      PARASOLLADY:          [:WATER, :FLYING, :ELECTRIC],
      HEXMANIAC:          [:GHOST],
      SECRETBASEEXPERT:          [:NORMAL, :GROUND, :ROCK, :GRASS],
      SCHOOLMATE_SR:         [:FAIRY, :NORMAL, :GRASS],
      SCHOOLMATE_JR:         [:FAIRY, :NORMAL, :GRASS],
      LEADER_Roxanne:  [:ROCK],
      LEADER_Brawly:  [:FIGHTING],
      LEADER_Wattson:  [:ELECTRIC],
      LEADER_Flannery:  [:FIRE],
      LEADER_Norman:  [:NORMAL],
      LEADER_Winona:  [:FLYING],
      LEADER_Tate:  [:PSYCHIC],
      LEADER_Liza:  [:PSYCHIC],
      LEADER_Wallace:  [:WATER],
      LEADER_Juan:  [:WATER],
      ELITEFOUR_Sidney:  [:PSYCHIC],
      ELITEFOUR_Phoebe:  [:GHOST],
      ELITEFOUR_Glacia:  [:ICE],
      ELITEFOUR_Drake:  [:DRAGON],
      CHAMPION_Steven:  [:STEEL],

      TEAM_AQUA_BOSS:  [:WATER],
      TEAM_MAGMA_BOSS:  [:GROUND],

    }
end