class BattledTrainer
  TRAINER_CLASS_FAVORITE_TYPES =
    {
      AROMALADY:      [:GRASS],
      BEAUTY:         [:FAIRY, :WATER, :NORMAL, :GRASS],
      BIKER:          [:POISON, :DARK],
      BIRDKEEPER:     [:FLYING, :NORMAL],
      BUGCATCHER:     [:BUG],
      BURGLAR:        [:FIRE, :DARK],
      CHANNELER:      [:GHOST, :PSYCHIC],
      CUEBALL:        [:FIGHTING],
      ENGINEER:       [:ELECTRIC, :STEEL],
      FISHERMAN:      [:WATER],
      GAMBLER:        [:NORMAL, :PSYCHIC],
      GENTLEMAN:      [:NORMAL, :STEEL],
      HIKER:          [:ROCK, :GROUND],
      JUGGLER:        [:PSYCHIC, :GHOST],
      LADY:           [:GRASS, :NORMAL],
      PAINTER:        [:NORMAL, :PSYCHIC],
      POKEMANIAC:     [:DRAGON, :GROUND, :WATER, :ELECTRIC, :STEEL, :FIRE, :GHOST,],
      POKEMONBREEDER: [:NORMAL, :GRASS],
      PROFESSOR:      [:NORMAL, :PSYCHIC],
      ROCKER:         [:ELECTRIC, :FIRE],
      RUINMANIAC:     [:GROUND, :ROCK],
      SAILOR:         [:WATER, :FIGHTING],
      SCIENTIST:      [:ELECTRIC, :STEEL, :POISON],
      SUPERNERD:      [:ELECTRIC, :PSYCHIC, :STEEL],
      TAMER:          [:NORMAL, :DARK],
      BLACKBELT:      [:FIGHTING],
      CRUSHGIRL:      [:FIGHTING],
      CAMPER:         [:BUG, :NORMAL, :GRASS],
      PICNICKER:      [:GRASS, :NORMAL],
      COOLTRAINER_M:  [:DRAGON, :STEEL, :FIRE],
      COOLTRAINER_F:  [:ICE, :PSYCHIC, :FAIRY],
      YOUNGSTER:      [:NORMAL, :BUG],
      LASS:           [:NORMAL, :GRASS],
      POKEMONRANGER_M: [:GRASS, :GROUND],
      POKEMONRANGER_F: [:GRASS, :WATER],
      PSYCHIC_M:      [:PSYCHIC, :GHOST],
      PSYCHIC_F:      [:PSYCHIC, :FAIRY],
      SWIMMER_M:      [:WATER],
      SWIMMER_F:      [:WATER, :ICE],
      SWIMMER2_M:     [:WATER],
      SWIMMER2_F:     [:WATER],
      TUBER_M:        [:WATER, :GROUND],
      TUBER_F:        [:WATER, :GROUND],
      TUBER2_M:       [:WATER, :GROUND],
      TUBER2_F:       [:WATER, :GROUND],
      COOLCOUPLE:     [:FIRE, :ICE],
      CRUSHKIN:       [:FIGHTING],
      SISANDBRO:      [:WATER, :GROUND],
      TWINS:          [:NORMAL, :GRASS],
      TWIN_1:          [:NORMAL, :WATER],
      TWIN_2:          [:NORMAL, :GRASS],
      YOUNGCOUPLE:    [:NORMAL, :PSYCHIC],
      SOCIALITE:      [:NORMAL],
      BUGCATCHER_F:   [:BUG],
      ROUGHNECK:      [:DARK, :FIGHTING],
      TEACHER:        [:PSYCHIC, :NORMAL],
      PRESCHOOLER_M:  [:NORMAL, :BUG],
      PRESCHOOLER_F:  [:NORMAL, :BUG],
      HAUNTEDGIRL_YOUNG:  [:GHOST],
      HAUNTEDGIRL:        [:GHOST, :DARK],
      CLOWN:          [:PSYCHIC, :BUG],
      NURSE:          [:NORMAL, :FAIRY],
      WORKER:         [:STEEL, :GROUND],
      COOLTRAINER_M2: [:FIGHTING, :STEEL, :DRAGON],
      COOLTRAINER_F2: [:PSYCHIC, :ICE, :DRAGON],
      FARMER:         [:GRASS, :GROUND, :NORMAL],
      PYROMANIAC:     [:FIRE],
      KIMONOGIRL:     [:PSYCHIC, :GHOST],
      SAGE:           [:PSYCHIC, :GHOST],
      PLAYER:         [:ICE, :FIGHTING],
      POLICE:         [:DARK, :FIGHTING],
      SKIER_F:        [:ICE],
      DELIVERYMAN:  [:NORMAL],
      RICHBOY: [:PSYCHIC, :FIRE, :GRASS, :WATER, :GROUND, :ROCK, :STEEL, :ELECTRIC],
      SCHOOLBOY: [:NORMAL, :ROCK, :BUG],
      SCHOOLGIRL: [:NORMAL, :ROCK, :GRASS],
      TEAM_AQUA_GRUNT_M: [:WATER, :ICE],
      TEAM_AQUA_GRUNT_F: [:WATER, :ICE],
      TEAM_MAGMA_GRUNT_M: [:FIRE, :GROUND],
      TEAM_MAGMA_GRUNT_F: [:FIRE, :GROUND],
      TEAM_MAGMAQUA_GRUNT_M: [:FIRE, :WATER],
      TEAM_MAGMAQUA_GRUNT_F: [:FIRE, :WATER],
      POKEFAN_M:    [:NORMAL, :ELECTRIC, :GRASS, :FIRE, :WATER],
      POKEFAN_F:   [:NORMAL, :ELECTRIC, :GRASS, :FIRE, :WATER],

      LEADER_Roxanne:     [:ROCK],
      LEADER_Brawly:      [:FIGHTING],
      LEADER_Wattson:    [:ELECTRIC],
      LEADER_Flannery:     [:FIRE],
      LEADER_Norman:     [:NORMAL],
      LEADER_Winona:     [:FLYING],
      LEADER_Tate:     [:PSYCHIC],
      LEADER_Liza:     [:PSYCHIC],
      LEADER_Wallace:    [:WATER],
      LEADER_Juan:     [:WATER],
      ELITEFOUR_Sidney:     [:PSYCHIC],
      ELITEFOUR_Phoebe:     [:GHOST],
      ELITEFOUR_Glacia:     [:ICE],
      ELITEFOUR_Drake:     [:DRAGON],
      CHAMPION_Steven:     [:STEEL],
    }
end