module GameData
  SPLIT_NAMES = [
    ["", ""],
    ["Bulba", "saur"],
    ["Ivy", "saur"],
    ["Venu", "saur"],
    ["Char", "mander"],
    ["Char", "meleon"],
    ["Char", "izard"],
    ["Squirt", "tle"],
    ["War", "tortle"],
    ["Blast", "toise"],
    ["Cater", "pie"],
    ["Meta", "pod"],
    ["Butter", "free"],
    ["Wee", "dle"],
    ["Kak", "una"],
    ["Bee", "drill"],
    ["Pid", "gey"],
    ["Pidge", "otto"],
    ["Pid", "geot"],
    ["Rat", "tata"],
    ["Rat", "icate"],
    ["Spear", "row"],
    ["Fear", "row"],
    ["Ek", "ans"],
    ["Ar", "bok"],
    ["Pika", "chu"],
    ["Rai", "chu"],
    ["Sand", "shrew"],
    ["Sand", "slash"],
    ["Nido", "ran"],
    ["Nido", "rina"],
    ["Nido", "queen"],
    ["Nido", "ran"],
    ["Nido", "rino"],
    ["Nido", "king"],
    ["Clef", "fairy"],
    ["Clef", "fable"],
    ["Vul", "pix"],
    ["Nine", "tales"],
    ["Jiggly", "puff"],
    ["Wiggly", "tuff"],
    ["Zu", "bat"],
    ["Gol", "bat"],
    ["Odd", "ish"],
    ["Gloo", "oom"],
    ["Vile", "plume"],
    ["Pa", "ras"],
    ["Para", "sect"],
    ["Veno", "nat"],
    ["Veno", "moth"],
    ["Dig", "lett"],
    ["Dug", "trio"],
    ["Meow", "th"],
    ["Per", "sian"],
    ["Psy", "duck"],
    ["Gol", "duck"],
    ["Man", "key"],
    ["Prime", "ape"],
    ["Growl", "lithe"],
    ["Arca", "nine"],
    ["Poli", "wag"],
    ["Poli", "whirl"],
    ["Poli", "wrath"],
    ["Ab", "ra"],
    ["Kada", "bra"],
    ["Ala", "kazam"],
    ["Ma", "chop"],
    ["Ma", "choke"],
    ["Ma", "champ"],
    ["Bell", "sprout"],
    ["Weepin", "bell"],
    ["Victree", "bell"],
    ["Tenta", "cool"],
    ["Tenta", "cruel"],
    ["Geo", "dude"],
    ["Grave", "ler"],
    ["Go", "lem"],
    ["Pony", "ta"],
    ["Rapi", "dash"],
    ["Slow", "poke"],
    ["Slow", "bro"],
    ["Magne", "mite"],
    ["Magne", "ton"],
    ["Far", "fetchd"],
    ["Do", "duo"],
    ["Do", "drio"],
    ["See", "eel"],
    ["Dew", "gong"],
    ["Gri", "mer"],
    ["Mu", "uk"],
    ["Shell", "der"],
    ["Cloy", "ster"],
    ["Gas", "tly"],
    ["Haun", "ter"],
    ["Gen", "gar"],
    ["On", "nix"],
    ["Drow", "zee"],
    ["Hyp", "no"],
    ["Krab", "by"],
    ["King", "ler"],
    ["Volt", "orb"],
    ["Electr", "ode"],
    ["Exegg", "cute"],
    ["Exeggu", "tor"],
    ["Cu", "bone"],
    ["Maro", "wak"],
    ["Hitmon", "lee"],
    ["Hitmon", "chan"],
    ["Licki", "tung"],
    ["Koff", "fing"],
    ["Wee", "zing"],
    ["Rhy", "horn"],
    ["Rhy", "don"],
    ["Chan", "sey"],
    ["Tan", "gela"],
    ["Kangas", "khan"],
    ["Hor", "sea"],
    ["Sea", "dra"],
    ["Gol", "deen"],
    ["Sea", "king"],
    ["Star", "yu"],
    ["Star", "mie"],
    ["Mr. ", "mime"],
    ["Scy", "ther"],
    ["Jyn", "nx"],
    ["Electa", "buzz"],
    ["Mag", "mar"],
    ["Pin", "sir"],
    ["Tau", "ros"],
    ["Magi", "karp"],
    ["Gyara", "dos"],
    ["Lap", "ras"],
    ["Dit", "to"],
    ["Ee", "vee"],
    ["Vapor", "eon"],
    ["Jolt", "eon"],
    ["Fla", "reon"],
    ["Pory", "gon"],
    ["Oma", "nyte"],
    ["Oma", "star"],
    ["Kabu", "to"],
    ["Kabu", "tops"],
    ["Aero", "dactyl"],
    ["Snor", "lax"],
    ["Arti", "cuno"],
    ["Zap", "dos"],
    ["Mol", "tres"],
    ["Dra", "tini"],
    ["Drago", "nair"],
    ["Drago", "nite"],
    ["Mew", "two"],
    ["Mew", "ew"],
    ["Chiko", "rita"],
    ["Bay", "leef"],
    ["Mega", "nium"],
    ["Cynda", "quil"],
    ["Qui", "lava"],
    ["Typh", "losion"],
    ["Toto", "dile"],
    ["Croco", "naw"],
    ["Fera", "ligatr"],
    ["Sen", "tret"],
    ["Fur", "ret"],
    ["Hoot", "hoot"],
    ["Noct", "owl"],
    ["Ledy", "ba"],
    ["Led", "ian"],
    ["Spina", "rak"],
    ["Aria", "dos"],
    ["Cro", "bat"],
    ["Chin", "chou"],
    ["Lan", "turn"],
    ["Pi", "chu"],
    ["Clef", "fa"],
    ["Iggly", "buff"],
    ["Toge", "pi"],
    ["Toge", "tic"],
    ["Na", "tu"],
    ["Xa", "tu"],
    ["Ma", "reep"],
    ["Flaa", "ffy"],
    ["Ampha", "ros"],
    ["Bell", "ossom"],
    ["Ma", "rill"],
    ["Azuma", "rill"],
    ["Sudo", "woodo"],
    ["Poli", "toed"],
    ["Hop", "pip"],
    ["Skip", "loom"],
    ["Jump", "luff"],
    ["Ai", "pom"],
    ["Sun", "kern"],
    ["Sun", "flora"],
    ["Yan", "ma"],
    ["Woo", "per"],
    ["Quag", "sire"],
    ["Esp", "eon"],
    ["Umb", "reon"],
    ["Mur", "krow"],
    ["Slow", "king"],
    ["Mis", "dreavus"],
    ["Un", "own"],
    ["Wob", "buffet"],
    ["Gira", "farig"],
    ["Pine", "co"],
    ["Forre", "tress"],
    ["Dun", "sparce"],
    ["Gli", "gar"],
    ["Stee", "lix"],
    ["Snub", "bull"],
    ["Gran", "bull"],
    ["Qwil", "fish"],
    ["Sci", "zor"],
    ["Shu", "ckle"],
    ["Hera", "cross"],
    ["Snea", "sel"],
    ["Teddi", "ursa"],
    ["Ursa", "ring"],
    ["Slug", "gma"],
    ["Mag", "cargo"],
    ["Swi", "nub"],
    ["Pilo", "swine"],
    ["Cor", "sola"],
    ["Remo", "raid"],
    ["Octi", "llery"],
    ["Deli", "bird"],
    ["Man", "tine"],
    ["Skar", "mory"],
    ["Houn", "dour"],
    ["Houn", "doom"],
    ["King", "dra"],
    ["Phan", "py"],
    ["Don", "phan"],
    ["Pory", "gon2"],
    ["Stan", "tler"],
    ["Smear", "gle"],
    ["Ty", "rogue"],
    ["Hitmon", "top"],
    ["Smoo", "chum"],
    ["Ele", "kid"],
    ["Mag", "by"],
    ["Mil", "tank"],
    ["Blis", "sey"],
    ["Rai", "kou"],
    ["En", "tei"],
    ["Sui", "cune"],
    ["Larvi", "tar"],
    ["Pupi", "tar"],
    ["Tyran", "itar"],
    ["Lu", "gia"],
    ["Ho-", "oh"],
    ["Cele", "bi"],
    ["Tree", "cko"],
    ["Gro", "vyle"],
    ["Scep", "tile"],
    ["Torch", "chic"],
    ["Com", "busken"],
    ["Bla", "ziken"],
    ["Mud", "kip"],
    ["Marsh", "tomp"],
    ["Swamp", "pert"],
    ["Pooch", "yena"],
    ["Might", "tyena"],
    ["Zig", "zagoon"],
    ["Lin", "noone"],
    ["Wurm", "ple"],
    ["Sil", "coon"],
    ["Beauti", "fly"],
    ["Cas", "scoon"],
    ["Dust", "tox"],
    ["Lo", "tad"],
    ["Lom", "bre"],
    ["Ludi", "colo"],
    ["Seed", "dot"],
    ["Nuz", "leaf"],
    ["Shift", "try"],
    ["Tail", "low"],
    ["Swell", "wellow"],
    ["Wing", "gull"],
    ["Peli", "liper"],
    ["Ral", "ts"],
    ["Kir", "lia"],
    ["Garde", "voir"],
    ["Sur", "skit"],
    ["Masque", "rain"],
    ["Shroom", "ish"],
    ["Bre", "loom"],
    ["Sla", "koth"],
    ["Vigo", "roth"],
    ["Sla", "king"],
    ["Nin", "cada"],
    ["Nin", "jask"],
    ["Shed", "inja"],
    ["Whism", "mur"],
    ["Loud", "dred"],
    ["Exp", "loud"],
    ["Maku", "hita"],
    ["Hari", "yama"],
    ["Azu", "rill"],
    ["Nose", "pass"],
    ["Skit", "itty"],
    ["Del", "catty"],
    ["Sabl", "eye"],
    ["Maw", "wile"],
    ["Ar", "on"],
    ["Lair", "ron"],
    ["Agg", "gron"],
    ["Med", "tite"],
    ["Medi", "cham"],
    ["Elect", "trike"],
    ["Mane", "tric"],
    ["Plus", "le"],
    ["Min", "un"],
    ["Vol", "beat"],
    ["Illu", "mise"],
    ["Rose", "elia"],
    ["Gulp", "in"],
    ["Swal", "ot"],
    ["Car", "vanha"],
    ["Sharp", "edo"],
    ["Wail", "mer"],
    ["Wail", "lord"],
    ["Nu", "mel"],
    ["Came", "rupt"],
    ["Tor", "koal"],
    ["Spo", "ink"],
    ["Grum", "pig"],
    ["Spin", "da"],
    ["Trap", "inch"],
    ["Vibra", "va"],
    ["Fly", "gon"],
    ["Cac", "nea"],
    ["Cact", "turne"],
    ["Swab", "lu"],
    ["Alta", "ria"],
    ["Zan", "goose"],
    ["Se", "viper"],
    ["Luna", "atone"],
    ["Sol", "lrock"],
    ["Bar", "boach"],
    ["Whis", "cash"],
    ["Corp", "phish"],
    ["Craw", "daunt"],
    ["Bal", "toy"],
    ["Clay", "dol"],
    ["Lil", "leep"],
    ["Crad", "dily"],
    ["Ano", "rith"],
    ["Arm", "aldo"],
    ["Fee", "bas"],
    ["Milo", "tic"],
    ["Cast", "form"],
    ["Kec", "eon"],
    ["Shup", "pet"],
    ["Ban", "nette"],
    ["Dus", "skull"],
    ["Dusc", "clops"],
    ["Tro", "pius"],
    ["Chime", "echo"],
    ["Ab", "sol"],
    ["Wy", "naut"],
    ["Sno", "runt"],
    ["Gla", "lie"],
    ["Sphe", "eal"],
    ["Sea", "leo"],
    ["Wal", "rein"],
    ["Clamp", "perl"],
    ["Hun", "tail"],
    ["Gore", "byss"],
    ["Reli", "canth"],
    ["Luv", "disc"],
    ["Ba", "agon"],
    ["Shel", "elgon"],
    ["Sala", "mence"],
    ["Bel", "dum"],
    ["Met", "tang"],
    ["Meta", "gross"],
    ["Regi", "rock"],
    ["Regi", "ice"],
    ["Regi", "steel"],
    ["La", "tias"],
    ["La", "tios"],
    ["Kyo", "ogre"],
    ["Grou", "don"],
    ["Ray", "quaza"],
    ["Ji", "rachi"],
    ["Deo", "xys"],
    ["Tur", "twig"],
    ["Gro", "tle"],
    ["Tor", "terra"],
    ["Chim", "char"],
    ["Mon", "ferno"],
    ["Infer", "nape"],
    ["Pip", "lup"],
    ["Prin", "plup"],
    ["Empo", "leon"],
    ["Starl", "arly"],
    ["Starav", "avia"],
    ["Starap", "raptor"],
    ["Bi", "doof"],
    ["Bi", "barel"],
    ["Kri", "ketot"],
    ["Kricke", "tune"],
    ["Shi", "nx"],
    ["Lu", "xio"],
    ["Lux", "ray"],
    ["Bu", "dew"],
    ["Rose", "rade"],
    ["Cran", "idos"],
    ["Ram", "pardos"],
    ["Shiel", "don"],
    ["Bastio", "don"],
    ["Bur", "my"],
    ["Worma", "dam"],
    ["Moth", "thim"],
    ["Comb", "bee"],
    ["Vesp", "quen"],
    ["Pachi", "risu"],
    ["Bui", "zel"],
    ["Float", "atzel"],
    ["Cher", "rubi"],
    ["Cherri", "rim"],
    ["Shell", "los"],
    ["Gastro", "trodon"],
    ["Ambi", "pom"],
    ["Drifl", "loon"],
    ["Drifb", "blim"],
    ["Bun", "eary"],
    ["Lop", "punny"],
    ["Mis", "magius"],
    ["Honch", "krow"],
    ["Glam", "meow"],
    ["Pur", "ugly"],
    ["Ching", "ling"],
    ["Stunk", "unky"],
    ["Skunt", "tank"],
    ["Bron", "zor"],
    ["Bronz", "zong"],
    ["Bon", "sly"],
    ["Mime", " Jr."],
    ["Happi", "piny"],
    ["Chat", "tot"],
    ["Spiri", "tomb"],
    ["Gib", "ble"],
    ["Gab", "bite"],
    ["Gar", "chomp"],
    ["Munch", "lax"],
    ["Rio", "olu"],
    ["Luca", "cario"],
    ["Hip", "potas"],
    ["Hippo", "powdon"],
    ["Sko", "rupi"],
    ["Drap", "ion"],
    ["Croa", "gunk"],
    ["Toxi", "croak"],
    ["Carni", "vine"],
    ["Finn", "neon"],
    ["Lumin", "ineon"],
    ["Man", "tyke"],
    ["Snov", "ver"],
    ["Aboma", "snow"],
    ["Weav", "vile"],
    ["Magne", "zone"],
    ["Licki", "licky"],
    ["Rhy", "perior"],
    ["Tan", "growth"],
    ["Electi", "vire"],
    ["Magmor", "mortar"],
    ["Toge", "kiss"],
    ["Yan", "mega"],
    ["Leaf", "feon"],
    ["Glace", "ceon"],
    ["Glis", "cor"],
    ["Mamo", "swine"],
    ["Pory", "gon-Z"],
    ["Gall", "lade"],
    ["Probo", "pass"],
    ["Dusk", "noir"],
    ["Fros", "lass"],
    ["Ro", "tom"],
    ["Ux", "xie"],
    ["Mes", "sprit"],
    ["Aze", "elf"],
    ["Dial", "alga"],
    ["Palk", "kia"],
    ["Heat", "tran"],
    ["Regi", "gigas"],
    ["Gira", "tina"],
    ["Cress", "selia"],
    ["Phio", "one"],
    ["Mana", "phy"],
    ["Dark", "rai"],
    ["Shay", "min"],
    ["Arc", "ceus"],
    ["Vict", "tini"],
    ["Sni", "vy"],
    ["Serv", "ine"],
    ["Serpe", "rior"],
    ["Te", "epig"],
    ["Pig", "ignite"],
    ["Emb", "boar"],
    ["Osha", "awott"],
    ["De", "ewott"],
    ["Samu", "rott"],
    ["Pat", "rat"],
    ["Watch", "hog"],
    ["Lill", "pup"],
    ["Herd", "erdier"],
    ["Stout", "land"],
    ["Purr", "loin"],
    ["Lie", "pard"],
    ["Pans", "ansage"],
    ["Sim", "misage"],
    ["Panse", "ansear"],
    ["Simis", "misear"],
    ["Panp", "pour"],
    ["Simip", "mipour"],
    ["Mun", "na"],
    ["Mush", "sharna"],
    ["Pido", "dove"],
    ["Tranq", "quill"],
    ["Unfe", "zant"],
    ["Blitz", "itzle"],
    ["Zeb", "strika"],
    ["Roggen", "rola"],
    ["Bold", "dore"],
    ["Giga", "lith"],
    ["Woob", "obat"],
    ["Swoo", "bat"],
    ["Drill", "bur"],
    ["Exca", "cadrill"],
    ["Aud", "dino"],
    ["Tim", "burr"],
    ["Gur", "durr"],
    ["Conkel", "eldurr"],
    ["Tym", "pole"],
    ["Palpi", "pitoad"],
    ["Seismi", "mitoad"],
    ["Thr", "roh"],
    ["Sa", "awk"],
    ["Sewa", "waddle"],
    ["Swad", "adloon"],
    ["Leav", "vanny"],
    ["Veni", "pede"],
    ["Whirli", "pede"],
    ["Scoli", "pede"],
    ["Cotton", "onee"],
    ["Whimsi", "cott"],
    ["Peti", "lil"],
    ["Lilli", "gant"],
    ["Bascu", "lin"],
    ["Sandi", "ile"],
    ["Kroko", "rok"],
    ["Krooko", "dile"],
    ["Daru", "maka"],
    ["Darman", "nitan"],
    ["Marac", "actus"],
    ["Dweb", "ebble"],
    ["Crust", "ustle"],
    ["Scra", "ggy"],
    ["Scraf", "ty"],
    ["Sigi", "lyph"],
    ["Ya", "mask"],
    ["Cofa", "grigus"],
    ["Tirt", "touga"],
    ["Carra", "costa"],
    ["Arch", "chen"],
    ["Arche", "cheops"],
    ["Trub", "bish"],
    ["Garb", "odor"],
    ["Zo", "rua"],
    ["Zoro", "ark"],
    ["Minc", "cino"],
    ["Cinc", "ccino"],
    ["Goth", "ita"],
    ["Gotho", "rita"],
    ["Gothi", "telle"],
    ["Solo", "sis"],
    ["Duo", "sion"],
    ["Reuni", "niclus"],
    ["Duck", "lett"],
    ["Swan", "anna"],
    ["Vani", "lite"],
    ["Vanil", "lish"],
    ["Vanill", "luxe"],
    ["Deer", "erling"],
    ["Saw", "buck"],
    ["Emol", "olga"],
    ["Karra", "blast"],
    ["Esca", "valier"],
    ["Foon", "gus"],
    ["Amoon", "guss"],
    ["Frill", "illish"],
    ["Jelli", "cent"],
    ["Alomo", "mola"],
    ["Jol", "tik"],
    ["Galvan", "tula"],
    ["Ferro", "seed"],
    ["Ferro", "thorn"],
    ["Kli", "ink"],
    ["Kla", "ang"],
    ["Klink", "klang"],
    ["Tyna", "amo"],
    ["Eel", "lektrik"],
    ["Eelek", "tross"],
    ["Elg", "gyem"],
    ["Behe", "eyem"],
    ["Lit", "wick"],
    ["Lamp", "pent"],
    ["Chandel", "lure"],
    ["Axe", "xew"],
    ["Frax", "xure"],
    ["Hax", "xorus"],
    ["Cub", "choo"],
    ["Bear", "artic"],
    ["Cryo", "gonal"],
    ["Shelm", "met"],
    ["Accel", "elgor"],
    ["Stun", "fisk"],
    ["Mie", "foo"],
    ["Mien", "shao"],
    ["Druddi", "digon"],
    ["Gole", "olett"],
    ["Golu", "lurk"],
    ["Pawn", "iard"],
    ["Bi", "sharp"],
    ["Bouf", "falant"],
    ["Ruff", "ufflet"],
    ["Brav", "viary"],
    ["Vull", "laby"],
    ["Mandi", "buzz"],
    ["Heatmo", "eatmor"],
    ["Dur", "ant"],
    ["Dei", "no"],
    ["Zwei", "lous"],
    ["Hy", "dreigon"],
    ["Larv", "esta"],
    ["Volca", "rona"],
    ["Cobal", "lion"],
    ["Terra", "kion"],
    ["Viri", "zion"],
    ["Tornad", "us"],
    ["Thund", "urus"],
    ["Reshi", "ram"],
    ["Zek", "rom"],
    ["Land", "orus"],
    ["Kyu", "rem"],
    ["Kel", "deo"],
    ["Melo", "etta"],
    ["Gene", "esect"],
    ["Ches", "pin"],
    ["Quil", "ladin"],
    ["Ches", "naught"],
    ["Fenne", "kin"],
    ["Brai", "xen"],
    ["Del", "phox"],
    ["Froa", "kie"],
    ["Frog", "adier"],
    ["Gre", "ninja"],
    ["Bunnel", "elby"],
    ["Diggers", "ersby"],
    ["Fletch", "ling"],
    ["Fletch", "inder"],
    ["Talon", "flame"],
    ["Scatter", "erbug"],
    ["Spew", "pa"],
    ["Vivi", "villon"],
    ["Litle", "itleo"],
    ["Pyro", "yroar"],
    ["Flabé", "bébé"],
    ["Flo", "loette"],
    ["Florg", "orges"],
    ["Skid", "kiddo"],
    ["Gogo", "goat"],
    ["Panch", "ancham"],
    ["Pango", "goro"],
    ["Furf", "frou"],
    ["Espu", "purr"],
    ["Meows", "stic"],
    ["Hon", "edge"],
    ["Doub", "blade"],
    ["Aegi", "slash"],
    ["Spritz", "itzee"],
    ["Aroma", "tisse"],
    ["Swir", "lix"],
    ["Slur", "puff"],
    ["Ink", "kay"],
    ["Mala", "lamar"],
    ["Bin", "nacle"],
    ["Barbar", "racle"],
    ["Skre", "relp"],
    ["Dragal", "galge"],
    ["Claunch", "auncher"],
    ["Claw", "witzer"],
    ["Heliop", "optile"],
    ["Heliol", "olisk"],
    ["Ty", "runt"],
    ["Tyran", "trum"],
    ["Ama", "aura"],
    ["Auro", "rorus"],
    ["Syl", "veon"],
    ["Hawl", "lucha"],
    ["Deden", "denne"],
    ["Car", "bink"],
    ["Goo", "my"],
    ["Sli", "goo"],
    ["Goo", "dra"],
    ["Klef", "ki"],
    ["Phant", "tump"],
    ["Tre", "venant"],
    ["Pump", "kaboo"],
    ["Gour", "geist"],
    ["Berg", "mite"],
    ["Ava", "lugg"],
    ["Noi", "bat"],
    ["Noi", "vern"],
    ["Xern", "neas"],
    ["Yvel", "veltal"],
    ["Zyga", "garde"],
    ["Dian", "cie"],
    ["Hoop", "oopa"],
    ["Volcan", "canion"],
    ["Rowl", "owlet"],
    ["Dart", "trix"],
    ["Decidu", "dueye"],
    ["Litte", "itten"],
    ["Torra", "cat"],
    ["Incine", "cineroar"],
    ["Popp", "plio"],
    ["Brion", "onne"],
    ["Prima", "marina"],
    ["Piki", "pek"],
    ["Trum", "beak"],
    ["Touca", "cannon"],
    ["Yung", "goos"],
    ["Gum", "shoos"],
    ["Grub", "bin"],
    ["Charja", "abug"],
    ["Vika", "volt"],
    ["Crab", "brawler"],
    ["Crabo", "ominable"],
    ["Ori", "corio"],
    ["Cutie", "tiefly"],
    ["Ribom", "bombee"],
    ["Rock", "ruff"],
    ["Lycan", "roc"],
    ["Wishi", "washi"],
    ["Mar", "eanie"],
    ["Tox", "apex"],
    ["Mudb", "bray"],
    ["Muds", "dale"],
    ["Dew", "pider"],
    ["Ara", "quanid"],
    ["Fo", "mantis"],
    ["Lu", "rantis"],
    ["More", "lull"],
    ["Shii", "notic"],
    ["Salan", "dit"],
    ["Sal", "azzle"],
    ["Stuff", "ful"],
    ["Be", "wear"],
    ["Bouns", "sweet"],
    ["Stee", "nee"],
    ["Tsar", "eena"],
    ["Com", "fey"],
    ["Oran", "guru"],
    ["Pass", "simian"],
    ["Wim", "pod"],
    ["Goli", "sopod"],
    ["Sandy", "gast"],
    ["Palo", "sand"],
    ["Pyuku", "muku"],
    ["Type:", " Null"],
    ["Silv", "ally"],
    ["Mini", "or"],
    ["Koma", "mala"],
    ["Turto", "nator"],
    ["Tegede", "maru"],
    ["Mimi", "kyu"],
    ["Brux", "ish"],
    ["Dram", "ampa"],
    ["Dhel", "mise"],
    ["Jang", "mo-o"],
    ["Haka", "mo-o"],
    ["Kom", "mo-o"],
    ["Tapu Ko", " Koko"],
    ["Tapu Le", " Lele"],
    ["Tapu Bu", " Bulu"],
    ["Tapu Fi", " Fini"],
    ["Cos", "smog"],
    ["Cosmo", "em"],
    ["Solga", "galeo"],
    ["Lun", "ala"],
    ["Nihi", "lego"],
    ["Buzz", "zwole"],
    ["Phero", "mosa"],
    ["Xurkit", "kitree"],
    ["Celeste", "steela"],
    ["Kart", "tana"],
    ["Guzz", "lord"],
    ["Necro", "zma"],
    ["Magear", "gearna"],
    ["Marsha", "shadow"],
    ["Poip", "ole"],
    ["Naga", "nadel"],
    ["Staka", "taka"],
    ["Blace", "phalon"],
    ["Zera", "ora"],
    ["Melt", "tan"],
    ["Mel", "metal"],
    ["Groo", "ookey"],
    ["Thwack", "ckey"],
    ["Rilla", "boom"],
    ["Scor", "bunny"],
    ["Rab", "boob"],
    ["Cinder", "ace"],
    ["Sob", "obble"],
    ["Drizz", "zile"],
    ["Intel", "eleon"],
    ["Skwo", "ovet"],
    ["Greed", "dent"],
    ["Rooki", "dee"],
    ["Corvis", "squire"],
    ["Corvik", "knight"],
    ["Blip", "lipbug"],
    ["Dott", "ottler"],
    ["Orbee", "beetle"],
    ["Nick", "kit"],
    ["Thiev", "vul"],
    ["Gossi", "fleur"],
    ["Elde", "goss"],
    ["Wool", "loo"],
    ["Dub", "wool"],
    ["Chew", "ewtle"],
    ["Dred", "ednaw"],
    ["Yamp", "amper"],
    ["Bolt", "tund"],
    ["Roly", "coly"],
    ["Cark", "arkol"],
    ["Coal", "lossal"],
    ["App", "plin"],
    ["Flapp", "apple"],
    ["Apple", "tun"],
    ["Sili", "cobra"],
    ["Sanda", "aconda"],
    ["Cramo", "morant"],
    ["Arro", "rokuda"],
    ["Barra", "skewda"],
    ["Toxe", "xel"],
    ["Toxtri", "tricity"],
    ["Sizzli", "zlipede"],
    ["Centi", "skorch"],
    ["Clobbo", "pus"],
    ["Grapp", "ploct"],
    ["Sinis", "tea"],
    ["Poltea", "teageist"],
    ["Hat", "tenna"],
    ["Hatt", "trem"],
    ["Hatte", "rene"],
    ["Impi", "dimp"],
    ["Mor", "grem"],
    ["Grimm", "snarl"],
    ["Obsta", "goon"],
    ["Perr", "serker"],
    ["Curs", "ursola"],
    ["Sir", "irfetch'd"],
    ["Mr. R", " Rime"],
    ["Rune", "erigus"],
    ["Milc", "cery"],
    ["Alcre", "cremie"],
    ["Fal", "links"],
    ["Pinc", "curchin"],
    ["Sn", "nom"],
    ["Frosmo", "osmoth"],
    ["Ston", "journer"],
    ["Eis", "cue"],
    ["Indeed", "deedee"],
    ["Morp", "peko"],
    ["Cuf", "fant"],
    ["Copper", "rajah"],
    ["Dracoz", "cozolt"],
    ["Arctoz", "tozolt"],
    ["Dracov", "covish"],
    ["Arctov", "tovish"],
    ["Dura", "ludon"],
    ["Dreep", "eepy"],
    ["Drak", "kloak"],
    ["Draga", "pult"],
    ["Zaci", "cian"],
    ["Zama", "zenta"],
    ["Eterna", "natus"],
    ["Kub", "fu"],
    ["Urshi", "shifu"],
    ["Zaru", "rude"],
    ["Regie", "leki"],
    ["Regid", "drago"],
    ["Glast", "strier"],
    ["Spect", "ctrier"],
    ["Caly", "rex"],
    ["Wyr", "deer"],
    ["Kleav", "vor"],
    ["Ursa", "luna"],
    ["Bascu", "legion"],
    ["Sneas", "sler"],
    ["Over", "qwil"],
    ["Enamo", "morus"],
  ]


  
  SPLIT_NAMES_FR = [
    ["", ""],
    ["Bulbi", "zarre"],
    ["Herbi", "zarre"],
    ["Flori", "zarre"],
    ["Sala", "mèche"],
    ["Rept", "incel"],
    ["Dracau", "feu"],
    ["Cara", "puce"],
    ["Cara", "baffe"],
    ["Tor", "tank"],
    ["Cheni", "pan"],
    ["Chrys", "acier"],
    ["Papi", "lusion"],
    ["Asp", "icot"],
    ["Coc", "onfort"],
    ["Dard", "argnan"],
    ["Rou", "cool"],
    ["Rou", "coups"],
    ["Rouc", "arnage"],
    ["Rat", "tata"],
    ["Ratt", "atac"],
    ["Piaf", "abec"],
    ["Rapas", "depic"],
    ["ab", "o"],
    ["Ar", "bok"],
    ["Pika", "chu"],
    ["Rai", "chu"],
    ["Sabe", "lette"],
    ["sablai", "reau"],
    ["Nido", "ran"],
    ["Nido", "rina"],
    ["Nido", "queen"],
    ["Nido", "ran"],
    ["Nido", "rino"],
    ["Nido", "king"],
    ["Mélo", "fée"],
    ["Mélo", "delfe"],
    ["Gou", "pix"],
    ["Feu", "nard"],
    ["Rondou", "dou"],
    ["Grodou", "dou"],
    ["Nosfe", "rapti"],
    ["Nosfe", "ralto"],
    ["Myst", "herbe"],
    ["Or", "tide"],
    ["Raff", "lesia"],
    ["Pa", "ras"],
    ["Para", "sect"],
    ["Mimi", "toss"],
    ["Aéro", "mite"],
    ["Taupi", "queur"],
    ["Trio", "pikeur"],
    ["Mia", "ouss"],
    ["Per", "sian"],
    ["Psyko", "kwak"],
    ["Akwa", "kwak"],
    ["Féro", "singe"],
    ["Colos", "singe"],
    ["Cani", "nos"],
    ["Arca", "nin"],
    ["Ptit", "ard"],
    ["Tê", "tarte"],
    ["Tar", "tard"],
    ["Ab", "ra"],
    ["Kada", "bra"],
    ["Ala", "kazam"],
    ["Ma", "choc"],
    ["Mach", "opeur"],
    ["Mack", "ogneur"],
    ["Chéti", "flor"],
    ["Bousti", "flor"],
    ["Empi", "flor"],
    ["Tenta", "cool"],
    ["Tenta", "cruel"],
    ["Racai", "llou"],
    ["Grava", "lanch"],
    ["Gro", "lem"],
    ["Pony", "ta"],
    ["Galo", "pa"],
    ["Ramo", "loss"],
    ["Flaga", "doss"],
    ["Magné", "ti"],
    ["Magné", "ton"],
    ["canar", "ticho"],
    ["Do", "duo"],
    ["Do", "drio"],
    ["Ota", "ria"],
    ["Laman", "tine"],
    ["Tad", "morv"],
    ["Grotad", "morv"],
    ["Koki", "yas"],
    ["Crusta", "bri"],
    ["Fanto", "minus"],
    ["Spec", "trum"],
    ["Ecto", "plasma"],
    ["On", "nix"],
    ["Sopo", "rifix"],
    ["Hypno", "made"],
    ["Krab", "by"],
    ["Krab", "boss"],
    ["Volt", "orbe"],
    ["Elec", "trode"],
    ["Noeu", "noeuf"],
    ["Noad", "koko"],
    ["Osse", "lait"],
    ["Ossa", "tueur"],
    ["Kick", "lee"],
    ["Ty", "gnon"],
    ["Exce", "langue"],
    ["Smo", "go"],
    ["Smo", "gogo"],
    ["Rhino", "corne"],
    ["Rhino", "Féroces"],
    ["Levei", "nard"],
    ["Saqued", "neu"],
    ["Kangou", "rex"],
    ["Hypo", "trempe"],
    ["Hypo","céan"],
    ["Poissi", "rène"],
    ["Poisso", "roy"],
    ["Sta", "ri"],
    ["Sta", "ross"],
    ["Mr. ", "mime"],
    ["Inse", "cateur"],
    ["Lippou", "tou"],
    ["Elek", "tek"],
    ["Mag", "mar"],
    ["Scara", "brute"],
    ["Tau", "ros"],
    ["Magi", "carpe"],
    ["Lévia", "tor"],
    ["Lokh", "lass"],
    ["Méta", "morph"],
    ["Évo", "li"],
    ["Aqua", "li"],
    ["Volt", "ali"],
    ["Pyro", "li"],
    ["Pory", "gon"],
    ["Amo", "nita"],
    ["Amoni", "star"],
    ["Kabu", "to"],
    ["Kabu", "tops"],
    ["Pté", "ra"],
    ["Ron", "flex"],
    ["Artik", "odin"],
    ["Elec", "thor"],
    ["Sulfu", "ra"],
    ["Mini", "draco"],
    ["Dra", "co"],
    ["Draco", "losse"],
    ["Mew", "two"],
    ["Mew", "ew"],
    ["Germi", "gnon"],
    ["Macro", "nium"],
    ["Mega", "nium"],
    ["Héri", "cendre"],
    ["Feuri", "sson"],
    ["Typh", "losion"],
    ["Kaimi", "nus"],
    ["Croco", "dil"],
    ["Aliga", "tueur"],
    ["Foui", "nette"],
    ["Foui", "nar"],
    ["Hoot", "hoot"],
    ["Noar", "fang"],
    ["Co", "xy"],
    ["Coxi", "claque"],
    ["Mimi", "gal"],
    ["Miga", "los"],
    ["Nos", "tenfer"],
    ["Lou", "pio"],
    ["Lan", "turn"],
    ["Pi", "chu"],
    ["Mé", "lo"],
    ["Toudou", "dou"],
    ["Toge", "pi"],
    ["Toge", "tic"],
    ["Na", "tu"],
    ["Xa", "tu"],
    ["Watt", "ouat"],
    ["Lain", "ergie"],
    ["Phar", "amp"],
    ["Joli", "flor"],
    ["Ma", "rill"],
    ["Azuma", "rill"],
    ["Simul", "arbre"],
    ["Tar", "paud"],
    ["Grani", "vol"],
    ["Flora", "vol"],
    ["Coto", "vol"],
    ["Capu", "main"],
    ["Tourne", "grin"],
    ["Hélia", "tronc"],
    ["Yan", "ma"],
    ["Axo", "loto"],
    ["Marai", "ste"],
    ["Men", "tali"],
    ["Noc", "tali"],
    ["Cor", "nèbre"],
    ["Roi", "gada"],
    ["Feufo", "rêve"],
    ["Zar", "bi"],
    ["Qulbu", "toké"],
    ["Gira", "farig"],
    ["Pomde", "pik"],
    ["Fore", "tress"],
    ["Inso", "lourdo"],
    ["Scor", "plane"],
    ["Stee", "lix"],
    ["Snub", "bull"],
    ["Gran", "bull"],
    ["Qwil", "fish"],
    ["Ciza", "yox"],
    ["Cara", "troc"],
    ["Sca", "rhino"],
    ["Far", "furet"],
    ["Teddi", "ursa"],
    ["Ursa", "ring"],
    ["lima", "gma"],
    ["Volca", "ropod"],
    ["Marca", "crin"],
    ["Cochi", "gnon"],
    ["Cora", "yon"],
    ["Rémo", "raid"],
    ["Octi", "llery"],
    ["Cadoi", "zo"],
    ["Déman", "ta"],
    ["Air", "mure"],
    ["Mal", "osse"],
    ["Démo", "losse"],
    ["Hypo", "roi"],
    ["Phan", "py"],
    ["Don", "phan"],
    ["Pory", "gon2"],
    ["Cerf", "rousse"],
    ["Queulo", "rior"],
    ["Debu", "gant"],
    ["Kapo", "era"],
    ["Lippou", "ti"],
    ["Ele", "kid"],
    ["Mag", "by"],
    ["Ecrém", "euh"],
    ["Leupho", "rie"],
    ["Rai", "kou"],
    ["En", "tei"],
    ["Sui", "cune"],
    ["Embry", "lex"],
    ["Ymph", "ect"],
    ["Tyra", "nocif"],
    ["Lu", "gia"],
    ["Ho-", "oh"],
    ["Cele", "bi"],
    ["Ar", "cko"],
    ["Mass", "ko"],
    ["Jun", "ko"],
    ["Poussi", "feu"],
    ["Gali", "feu"],
    ["Brasé", "gali"],
    ["Go", "bou"],
    ["Flo", "bio"],
    ["Lag", "gron"],
    ["Medh", "yèna"],
    ["Grah", "yèna"],
    ["Zigza", "ton"],
    ["Lin", "éon"],
    ["Cheni", "potte"],
    ["Armu", "lys"],
    ["Charmi", "llon"],
    ["Blinda", "lys"],
    ["Papi", "nox"],
    ["Nénu", "piod"],
    ["Lom", "bre"],
    ["Ludi", "colo"],
    ["Grani", "piot"],
    ["Pif", "euil"],
    ["Tenga", "lice"],
    ["Niron", "delle"],
    ["Hélé", "delle"],
    ["Goé", "lise"],
    ["Beki", "pan"],
    ["Tar", "sal"],
    ["Kir", "lia"],
    ["Garde", "voir"],
    ["Arak", "do"],
    ["Mask", "adra"],
    ["Bali", "gnon"],
    ["Chapi", "gnon"],
    ["Pare", "cool"],
    ["Vigo", "roth"],
    ["Mona", "flèmit"],
    ["Nin", "gale"],
    ["Nin", "jask"],
    ["Mun", "ja"],
    ["Chuch", "mur"],
    ["Ram", "boum"],
    ["Brouha", "bam"],
    ["Maku", "hita"],
    ["Hari", "yama"],
    ["Azu", "rill"],
    ["Tari", "nor"],
    ["Ski", "tty"],
    ["Del", "catty"],
    ["Téné", "fix"],
    ["Mysdi", "bule"],
    ["Gale", "kid"],
    ["Gale", "gon"],
    ["Gale", "king"],
    ["Médit", "ikka"],
    ["Charm", "ina"],
    ["Dyna", "volt"],
    ["Élecsp", "rint"],
    ["Posi", "pi"],
    ["Néga", "pi"],
    ["Muci", "ole"],
    ["Lumi", "vole"],
    ["Rose", "elia"],
    ["Glou", "pti"],
    ["Aval", "tout"],
    ["Car", "vanha"],
    ["Sharp", "edo"],
    ["Wail", "mer"],
    ["Wail", "lord"],
    ["Chamal", "lot"],
    ["Came", "rupt"],
    ["Char", "tor"],
    ["Spo", "ink"],
    ["Gro", "ret"],
    ["Spin", "da"],
    ["Krak", "noix"],
    ["Vibra", "ninf"],
    ["Libé", "gon"],
    ["Cac", "nea"],
    ["Cact", "turne"],
    ["Tyl", "ton"],
    ["Alta", "ria"],
    ["Mang", "riff"],
    ["Se", "viper"],
    ["Sélé", "roc"],
    ["Sola", "roc"],
    ["Bar", "loche"],
    ["Barb", "icha"],
    ["Écra", "pince"],
    ["Colh", "omard"],
    ["Balb", "uto"],
    ["Kaor", "ine"],
    ["Lil", "ia"],
    ["Vaci", "lys"],
    ["Ano", "rith"],
    ["Arm", "aldo"],
    ["Bar", "pau"],
    ["Milob", "ellus"],
    ["Morp", "héo"],
    ["Kecl", "eon"],
    ["Poli", "chombr"],
    ["Bran", "nette"],
    ["Skelé", "nox"],
    ["Téra", "clope"],
    ["Tro", "pius"],
    ["Éo", "ko"],
    ["Ab", "sol"],
    ["Oké", "oké"],
    ["Stal", "gamin"],
    ["Onig", "lali"],
    ["Oba", "lie"],
    ["Phog", "leur"],
    ["Kaim", "orse"],
    ["Coqui", "perl"],
    ["Serp", "ang"],
    ["Gore", "byss"],
    ["Reli", "canth"],
    ["Lov", "disc"],
    ["Dra", "by"],
    ["Drac", "khaus"],
    ["Drat", "tak"],
    ["Ter", "hal"],
    ["Mét", "ang"],
    ["Méta", "losse"],
    ["Regi", "rock"],
    ["Regi", "ice"],
    ["Regi", "steel"],
    ["La", "tias"],
    ["La", "tios"],
    ["Kyo", "ogre"],
    ["Grou", "don"],
    ["Ray", "quaza"],
    ["Ji", "rachi"],
    ["Deo", "xys"],
    ["Torti", "pouss"],
    ["Bos", "kara"],
    ["Tor", "terra"],
    ["Ouisti", "cram"],
    ["Chimp", "enfeu"],
    ["Simia", "braz"],
    ["Tip", "louf"],
    ["Prin", "plouf"],
    ["Pingo", "léon"],
    ["Étou", "rmi"],
    ["Étour", "vol"],
    ["Étoura", "ptor"],
    ["Keun", "otor"],
    ["Cast", "orno"],
    ["Crik", "zik"],
    ["Mélo", "krik"],
    ["Li", "xy"],
    ["Lu", "xio"],
    ["Lux", "ray"],
    ["Rozb", "outon"],
    ["Rose", "rade"],
    ["Kran", "idos"],
    ["Char", "kos"],
    ["Dino", "clier"],
    ["Bastio", "don"],
    ["Chen", "iti"],
    ["Cheni", "selle"],
    ["Papi", "lord"],
    ["Apit", "rini"],
    ["Api", "reine"],
    ["Pachi", "risu"],
    ["Musté", "bouée"],
    ["Musté", "flott"],
    ["Ceri", "bou"],
    ["Ceri", "flor"],
    ["San", "coki"],
    ["Trito", "sor"],
    ["Capid", "extre"],
    ["Baud", "rive"],
    ["Grod", "rive"],
    ["Bun", "eary"],
    ["Lapo", "reille"],
    ["Magi", "rêve"],
    ["Cor", "boss"],
    ["Chag", "lam"],
    ["Chaff", "reux"],
    ["Koril", "lon"],
    ["Moufou", "ette"],
    ["Skunt", "tank"],
    ["Mouff", "lair"],
    ["Arché", "odong"],
    ["Man", "zaï"],
    ["Mime", " Jr."],
    ["Pti", "ravi"],
    ["Pij", "ako"],
    ["Spiri", "tomb"],
    ["Gri", "knot"],
    ["Carm", "ache"],
    ["Carcha", "crok"],
    ["Goin", "frex"],
    ["Rio", "olu"],
    ["Luca", "cario"],
    ["Hip", "potas"],
    ["Hippo", "docus"],
    ["Rap", "ion"],
    ["Drap", "ion"],
    ["Crad", "opaud"],
    ["Coa", "tox"],
    ["Vort", "ente"],
    ["Éca", "yon"],
    ["Lumin", "ineon"],
    ["Babi", "manta"],
    ["Bliz", "zi"],
    ["Blizza", "roi"],
    ["Dimo", "ret"],
    ["Magne", "zone"],
    ["Coud", "langue"],
    ["Rhina", "stoc"],
    ["Boul", "deneu"],
    ["Éleka", "ble"],
    ["Maga", "non"],
    ["Toge", "kiss"],
    ["Yan", "mega"],
    ["Phyl", "lali"],
    ["Glace", "ceon"],
    ["Giv", "rali"],
    ["Mamm", "ochon"],
    ["Pory", "gon-Z"],
    ["Gal", "lame"],
    ["Tari", "norme"],
    ["Noctu", "noir"],
    ["Moma", "rtik"],
    ["Moti", "sma"],
    ["Créh", "elf"],
    ["Créfo", "llet"],
    ["Créf", "adet"],
    ["Dial", "alga"],
    ["Palk", "kia"],
    ["Heat", "tran"],
    ["Regi", "gigas"],
    ["Gira", "tina"],
    ["Cress", "selia"],
    ["Phio", "one"],
    ["Mana", "phy"],
    ["Dark", "rai"],
    ["Shay", "min"],
    ["Arc", "ceus"],
    ["Vict", "tini"],
    ["Vipél", "ierre"],
    ["Lian", "aja"],
    ["Maja", "spic"],
    ["Grui", "kui"],
    ["Grot", "ichon"],
    ["Roit", "iflam"],
    ["Moust", "illon"],
    ["Mate", "loutre"],
    ["Clami", "ral"],
    ["Raten", "tif"],
    ["Mira", "dar"],
    ["Ponc", "hiot"],
    ["Pon", "chien"],
    ["Mast", "ouffe"],
    ["Chac", "ripan"],
    ["Léop", "ardus"],
    ["Feuil", "lajou"],
    ["Feuil", "outan"],
    ["Flama", "jou"],
    ["Flam", "outan"],
    ["Flota", "jou"],
    ["Flot", "outan"],
    ["Mun", "na"],
    ["Mushana", "ana"],
    ["Poichi", "geon"],
    ["Colom", "beau"],
    ["Déflai", "san"],
    ["Zébi", "bron"],
    ["Zébl", "itz"],
    ["Nodul", "ithe"],
    ["Géol", "ithe"],
    ["Giga", "lith"],
    ["Chovs", "ourir"],
    ["Rhino", "love"],
    ["Roto", "taupe"],
    ["Mino", "taupe"],
    ["Nanmé", "ouïe"],
    ["Charp", "enti"],
    ["Ouvri", "fier"],
    ["Béto", "chef"],
    ["Trit", "onde"],
    ["Batr", "acné"],
    ["Crapus", "tule"],
    ["Judo", "krak"],
    ["Kara", "clée"],
    ["Larvey", "ette"],
    ["Couver", "dure"],
    ["Mant", "ernel"],
    ["Veni", "patte"],
    ["Scobo", "lide"],
    ["Bruta", "pode"],
    ["Doud", "ouvet"],
    ["Farfa", "duvet"],
    ["Chloro", "bule"],
    ["Fragi", "lady"],
    ["Bargan", "tua"],
    ["Masc", "aïman"],
    ["Esc", "roco"],
    ["Croco", "rible"],
    ["Darum", "arond"],
    ["Daru", "macho"],
    ["Mara", "cachi"],
    ["Crabi", "coque"],
    ["Craba", "raque"],
    ["Baggi", "guane"],
    ["Bag", "gaïd"],
    ["Cryp", "téro"],
    ["Tuta", "feh"],
    ["Tutan", "kafer"],
    ["Carap", "agos"],
    ["Mégap", "agos"],
    ["Arkéa", "pti"],
    ["Aérop", "téryx"],
    ["Miami", "asme"],
    ["Mias", "max"],
    ["Zo", "rua"],
    ["Zoro", "ark"],
    ["Chinch", "idou"],
    ["Pashm", "illa"],
    ["Scru", "tella"],
    ["Mesmé", "rella"],
    ["Sidé", "rella"],
    ["Nuc", "léos"],
    ["Mé", "ios"],
    ["Sym", "bios"],
    ["Coua", "neton"],
    ["Lakmé", "cygne"],
    ["Sor", "bébé"],
    ["Sor", "boul"],
    ["Sorbou", "boul"],
    ["Vival", "daim"],
    ["Hay", "daim"],
    ["Emol", "olga"],
    ["Cara", "bing"],
    ["Lanç", "argot"],
    ["Tromp", "ignon"],
    ["Gau", "let"],
    ["Vis", "kuse"],
    ["Moy", "ade"],
    ["Mam", "anbo"],
    ["Stati", "tik"],
    ["Myga", "volt"],
    ["Grin", "dur"],
    ["Noa", "cier"],
    ["Ti", "ic"],
    [" Cli", "ic"],
    [" Cliti", "clic"],
    [" Anch", "watt"],
    ["Lampé", "roie"],
    ["Ohmas", "sacre"],
    ["Lew", "sor"],
    ["Nei", "tram"],
    ["Funé", "cire"],
    ["Mélan", "colux"],
    ["Lugu", "labre"],
    ["Coupe", "notte"],
    ["Inci", "sache"],
    ["Tranch", "odon"],
    ["Pola", "rhume"],
    ["Pola", "griffe"],
    ["Hexa", "gel"],
    ["Escar", "gaume"],
    ["Lima", "speed"],
    ["Lim", "onde"],
    ["Kung", "fouine"],
    ["Shao", "fouine"],
    ["Drak", "karmin"],
    ["Grin", "golem"],
    ["Gole", "mastoc"],
    ["Scal", "pion"],
    ["Scal", "proie"],
    ["Fri", "son"],
    ["Furai", "glon"],
    ["Gueri", "aigle"],
    ["Vost", "ourno"],
    ["Vautu", "trice"],
    ["Afla", "manoir"],
    ["Fer", "mite"],
    ["Solo", "chi"],
    ["Dia", "mat"],
    ["Triox", "hydre"],
    ["Pyro", "nille"],
    ["Py", "rax"],
    ["Cobal", "tium"],
    ["Terra", "kium"],
    ["Viri", "dium"],
    ["Bor", "éas"],
    ["Fulgu", "ris"],
    ["Reshi", "ram"],
    ["Zek", "rom"],
    ["Démé", "téros"],
    ["Kyu", "rem"],
    ["Kel", "deo"],
    ["Melo", "etta"],
    ["Gene", "esect"],
    ["Mari", "sson"],
    ["Bogué", "risse"],
    ["Blindé", "pique"],
    ["Feun", "nec"],
    ["Rous", "sil"],
    ["Goupe", "lin"],
    ["Gre", "nousse"],
    ["Croâ", "poral"],
    ["Amphi", "nobi"],
    ["Sape", "reau"],
    ["Excava", "renne"],
    ["Passe", "rouge"],
    ["Brai", "sillon"],
    ["Flambu", "sard"],
    ["Lépi", "donille"],
    ["Péré", "grain"],
    ["Prism", "millon"],
    ["Hélion", "ceau"],
    ["Némé", "lios"],
    ["Flabé", "bébé"],
    ["Flo", "loette"],
    ["Florg", "orges"],
    ["Cabri", "olaine"],
    ["Che", "vroum"],
    ["Pandes", "piègle"],
    ["Pandar", "bare"],
    ["Coua", "farel"],
    ["Psy", "stigri"],
    ["Misti", "grix"],
    ["Monor", "pale"],
    ["Dimo", "clès"],
    ["Exa", "gide"],
    ["Fluve", "tin"],
    ["Coco", "tine"],
    ["Sucro", "quin"],
    ["Cupca", "naille"],
    ["Sepia", "top"],
    ["Sepia", "troce"],
    ["Oper", "mine"],
    ["Golgo", "pathe"],
    ["Vena", "algue"],
    ["Krava", "rech"],
    ["Flin", "gouste"],
    ["Gamb", "blast"],
    ["Galv", "aran"],
    ["Iguo", "olta"],
    ["Ptyra", "nidur"],
    ["Rex", "illius"],
    ["Ama", "gara"],
    ["Drag", "mara"],
    ["Nymph", "phali"],
    ["Bruta", "libé"],
    ["Deden", "denne"],
    ["Stra", "ssie"],
    ["Mucus", "scule"],
    ["Colimu", "cus"],
    ["Muplo", "docus"],
    ["Trous", "selin"],
    ["Brocé", "lôme"],
    ["Dessé", "liande"],
    ["Pitrou", "ouille"],
    ["Banshi", "trouye"],
    ["Grela", "con"],
    ["Séra", "crawl"],
    ["Soni", "strelle"],
    ["Bruy", "vern"],
    ["Xern", "neas"],
    ["Yvel", "veltal"],
    ["Zyga", "garde"],
    ["Dian", "cie"],
    ["Hoop", "oopa"],
    ["Volcan", "canion"],
    ["Brindi", "dibou"],
    ["Efflè", "che"],
    ["Arché", "éduc"],
    ["Flamia", "iaou"],
    ["Matou", "feu"],
    ["Félin", "ferno"],
    ["Ota", "quin"],
    ["Otar", "lette"],
    ["Orato", "toria"],
    ["Pica", "assaut"],
    ["Piclai", "airon"],
    ["Bazou", "can"],
    ["Manglou", "ton"],
    ["Argou", "ouste"],
    ["Larvi", "bul"],
    ["Chrysa", "apile"],
    ["Luca", "anon"],
    ["Craba", "garre"],
    ["Crabo", "ominable"],
    ["Plume", "line"],
    ["Bomby", "dou"],
    ["Rubom", "belle"],
    ["Roca", "abot"],
    ["Louga", "aroc"],
    ["Frouss", "ardine"],
    ["Voras", "térie"],
    ["Prédas", "térie"],
    ["Tibou", "oudet"],
    ["Bour", "rinos"],
    ["Ara", "qua"],
    ["Taren", "bulle"],
    ["Mi", "mantis"],
    ["Flora", "mantis"],
    ["Spodo", "dodo"],
    ["Lampi", "ignon"],
    ["Tri", "tox"],
    ["Mala", "mandre"],
    ["Nounou", "rson"],
    ["Chel", "ours"],
    ["Croq", "uine"],
    ["Can", "dine"],
    ["Sucr", "reine"],
    ["Guéri", "lande"],
    ["Gourou", "outan"],
    ["Quart", "ermac"],
    ["Sovki", "pou"],
    ["Sarmu", "uraï"],
    ["Baca", "bouh"],
    ["Trépas", "sable"],
    ["Concom", "baffe"],
    ["Ty:", " pe:0"],
    ["Silva", "allié"],
    ["Mété", "éno"],
    ["Dodo", "doala"],
    ["Bouma", "ata"],
    ["Togade", "maru"],
    ["Mimi", "qui"],
    ["Denti", "crisse"],
    ["Draï", "ïeul"],
    ["Sinis", "trail"],
    ["Bébé", "caille"],
    ["Eca", "aïd"],
    ["Ekaï", "seur"],
    ["Toko", " rico"],
    ["Toko", " piyon"],
    ["Toko", " toro"],
    ["Toko", " pisco"],
    ["Cos", "smog"],
    ["Cosmo", "vum"],
    ["Solga", "galeo"],
    ["Lun", "ala"],
    ["Zéro", "oïd"],
    ["Mous", "coto"],
    ["Cancre", "love"],
    ["Câbli", "lifère"],
    ["Bamboi", "selle"],
    ["Kata", "gami"],
    ["Englou", "tyran"],
    ["Necro", "zma"],
    ["Magear", "gearna"],
    ["Marsha", "shadow"],
    ["Vemi", "ni"],
    ["Mandri", "llon"],
    ["Ama", "ama"],
    ["Pierro", "teknik"],
    ["Zera", "ora"],
    ["Melt", "tan"],
    ["Mel", "metal"],
    ["Ouis", "tempo"],
    ["Bada", "bouin"],
    ["Gory", "thmic"],
    ["Flambi", "no"],
    ["Lapy", "ro"],
    ["Pyro", "but"],
    ["Larmé", "léon"],
    ["Arro", "zard"],
    ["Lézar", "gus"],
    ["Rongour", "mand"],
    ["Rongri", "gou"],
    ["Mini", "sange"],
    ["Bleu", "seille"],
    ["Corva", "illus"],
    ["Larva", "dar"],
    ["Coléo", "dome"],
    ["Astro", "nelle"],
    ["Goupi", "lou"],
    ["Rouble", "nard"],
    ["Tourni", "coton"],
    ["Blan", "coton"],
    ["Moumou", "ton"],
    ["Moumou", "flon"],
    ["Khélo", "crok"],
    ["Torga", "mord"],
    ["Voltou", "tou"],
    ["Fulgu", "dog"],
    ["Char", "bi"],
    ["Wago", "mine"],
    ["Monthra", "cite"],
    ["Ver", "pom"],
    ["Pom", "drapi"],
    ["Drata", "tin"],
    ["Duna", "ja"],
    ["Duna", "conda"],
    ["Nigo", "sier"],
    ["Embro", "chet"],
    ["Hasta", "cuda"],
    ["Toxi", "zap"],
    ["Salar", "sen"],
    ["Grille", "pattes"],
    ["Scolo", "cendre"],
    ["Poul", "paf"],
    ["Kra", "kos"],
    ["Thé", "ffroi"],
    ["Polthé", "geist"],
    ["Bibi", "chut"],
    ["Chapo", "tus"],
    ["Sorci", "lence"],
    ["Grima", "lin"],
    ["Fourbe", "lin"],
    ["Ango", "liath"],
    ["Ix", "on"],
    ["Berser", "katt"],
    ["Cora", "yôme"],
    ["Palar", "ticho"],
    ["Mr. ", " Glaquette"],
    ["Tuté", "tékri"],
    ["Crè", "mi"],
    ["Char", "milla"],
    ["Hexa", "dron"],
    ["Watt", "apik"],
    ["Friss", "onille"],
    ["Belde", "neige"],
    ["Dol", "man"],
    ["Beka", "glacon"],
    ["Wime", "ssir"],
    ["Morp", "peko"],
    ["Chari", "bari"],
    ["Pachy", "radjah"],
    ["Galva", "gon"],
    ["Galva", "gla"],
    ["Hydra", "gon"],
    ["Hydra", "gla"],
    ["Dural", "gon"],
    ["Fant", "yrm"],
    ["Dispa", "reptil"],
    ["Lansso", "rien"],
    ["Zaci", "cian"],
    ["Zama", "zenta"],
    ["Ether", "natos"],
    ["Wush", "ours"],
    ["Shif", "ours"],
    ["Zaru", "rude"],
    ["Regie", "leki"],
    ["Regid", "drago"],
    ["Blizz", "eval"],
    ["Spectre", "eval"],
    ["Sylve", "roy"],
    ["Cerby", "yllin"],
    ["Haché", "cateur"],
    ["Ursa", "king"],
    ["Para", "gruel"],
    ["Farf", "furex"],
    ["Qwil", "pik"],
    ["Amo", "vénus"],
  ]
  NAT_DEX_MAPPING = {
    252 => 298,
    253 => 360,
    254 => 424,
    255 => 429,
    256 => 430,
    257 => 438,
    258 => 439,
    259 => 440,
    260 => 446,
    261 => 458,
    262 => 461,
    263 => 462,
    264 => 463,
    265 => 464,
    266 => 465,
    267 => 466,
    268 => 467,
    269 => 468,
    270 => 469,
    271 => 470,
    272 => 471,
    273 => 472,
    274 => 473,
    275 => 474,
    276 => 252,
    277 => 253,
    278 => 254,
    279 => 255,
    280 => 256,
    281 => 257,
    282 => 258,
    283 => 259,
    284 => 260,
    285 => 280,
    286 => 281,
    287 => 282,
    288 => 475,
    289 => 292,
    290 => 352,
    291 => 374,
    292 => 375,
    293 => 376,
    294 => 399,
    295 => 442,
    296 => 448,
    297 => 443,
    298 => 444,
    299 => 445,
    300 => 303,
    301 => 345,
    302 => 346,
    303 => 347,
    304 => 348,
    305 => 408,
    306 => 409,
    307 => 410,
    308 => 411,
    309 => 289,
    310 => 359,
    311 => 355,
    312 => 356,
    313 => 477,
    314 => 321,
    315 => 493,
    316 => 387,
    317 => 388,
    318 => 389,
    319 => 390,
    320 => 391,
    321 => 392,
    322 => 393,
    323 => 394,
    324 => 395,
    325 => 299,
    326 => 476,
    327 => 679,
    328 => 680,
    329 => 681,
    330 => 624,
    331 => 625,
    332 => 405,
    333 => 306,
    334 => 330,
    335 => 350,
    336 => 373,
    337 => 601,
    338 => 571,
    339 => 700,
    340 => 382,
    341 => 383,
    342 => 384,
    343 => 483,
    344 => 484,
    345 => 487,
    346 => 486,
    347 => 491,
    348 => 649,
    349 => 643,
    350 => 644,
    351 => 646,
    352 => 407,
    353 => 426,
    354 => 428,
    355 => 286,
    356 => 291,
    357 => 354,
    358 => 479,
    359 => 579,
    360 => 547,
    361 => 553,
    362 => 563,
    363 => 596,
    364 => 598,
    365 => 607,
    366 => 608,
    367 => 609,
    368 => 612,
    369 => 623,
    370 => 771,
    371 => 707,
    372 => 663,
    373 => 778,
    374 => 637,
    375 => 633,
    376 => 634,
    377 => 635,
    378 => 380,
    379 => 381,
    380 => 386,
    381 => 385,
    382 => 290,
    383 => 400,
    384 => 447,
    385 => 287,
    386 => 288,
    387 => 320,
    388 => 403,
    389 => 404,
    390 => 304,
    391 => 305,
    392 => 328,
    393 => 329,
    394 => 349,
    395 => 371,
    396 => 372,
    397 => 599,
    398 => 600,
    399 => 570,
    400 => 406,
    401 => 315,
    402 => 425,
    403 => 427,
    404 => 285,
    405 => 353,
    406 => 577,
    407 => 578,
    408 => 546,
    409 => 551,
    410 => 552,
    411 => 562,
    412 => 595,
    413 => 597,
    414 => 610,
    415 => 611,
    416 => 622,
    417 => 661,
    418 => 662,
    419 => 636,
    420 => 618,
    #new pokes
    421 => 302,
    422 => 543,
    423 => 544,
    424 => 545,
    425 => 696,
    426 => 697,
    427 => 361,
    428 => 362,
    429 => 478,
    430 => 741,
    431 => 741,
    432 => 741,
    433 => 741,
    434 => 568,
    435 => 569,
    436 => 318,
    437 => 319,
    438 => 708,
    439 => 709,
    440 => 714,
    441 => 715,
    442 => 333,
    443 => 334,
    444 => 704,
    445 => 705,
    446 => 706,
    447 => 377,
    448 => 378,
    449 => 379,
    450 => 800,
    451 => 759,
    452 => 760,
    453 => 781,
    454 => 747,
    455 => 748,
    456 => 701,
    457 => 331,
    458 => 332,
    459 => 769,
    460 => 770,
    461 => 698,
    462 => 699,
    463 => 744,
    464 => 745,
    465 => 745,
    466 => 648,
    467 => 648,
    468 => 488,
    469 => 779,
    470 => 800,
    471 => 782,
    472 => 783,
    473 => 784,
    474 => 767,
    475 => 768,
    476 => 753,
    477 => 754,
    478 => 703,
    479 => 650,
    480 => 651,
    481 => 652,
    482 => 653,
    483 => 654,
    484 => 655,
    485 => 656,
    486 => 657,
    487 => 658,
    488 => 324,
    489 => 710,
    490 => 711,
    491 => 684,
    492 => 685,
    493 => 559,
    494 => 560,
    495 => 270,
    496 => 271,
    497 => 272,
    498 => 774,
    499 => 774,
    500 => 719,
    501 => 370,
    502	=>	261	,
    503	=>	262	,
    504	=>	263	,
    505	=>	264	,
    506	=>	265	,
    507	=>	266	,
    508	=>	267	,
    509	=>	268	,
    510	=>	269	,
    511	=>	273	,
    512	=>	274	,
    513	=>	275	,
    514	=>	276	,
    515	=>	277	,
    516	=>	278	,
    517	=>	279	,
    518	=>	283	,
    519	=>	284	,
    520	=>	293	,
    521	=>	294	,
    522	=>	295	,
    523	=>	296	,
    524	=>	297	,
    525	=>	300	,
    526	=>	301	,
    527	=>	307	,
    528	=>	308	,
    529	=>	309	,
    530	=>	310	,
    531	=>	311	,
    532	=>	312	,
    533	=>	313	,
    534	=>	314	,
    535	=>	316	,
    536	=>	317	,
    537	=>	322	,
    538	=>	323	,
    539	=>	325	,
    540	=>	326	,
    541	=>	327	,
    542	=>	335	,
    543	=>	336	,
    544	=>	337	,
    545	=>	338	,
    546	=>	339	,
    547	=>	340	,
    548	=>	341	,
    549	=>	342	,
    550	=>	343	,
    551	=>	344	,
    552	=>	351	,
    553	=>	351	,
    554	=>	351	,
    555	=>	351	,
    556	=>	357	,
    557	=>	433	,
    558	=>	358	,
    559	=>	363	,
    560	=>	364	,
    561	=>	365	,
    562	=>	366	,
    563	=>	367	,
    564	=>	368	,
    565	=>	369	,
  }
end

