##############
# ANIMATIONS
################
DUST_ANIMATION_ID=2
VIRUS_ANIMATION_ID=10

TELEPORT_ANIMATION_ID=32
EXPLODE_ANIMATION=15
SPARKLE_ANIMATION=29

PUDDLE_ANIMATION_ID = 31



EXCLAMATION_ANIMATION_ID = 3

QUESTION_MARK_ANIMATION_ID = 4
ANGRY_ANIMATION_ID = 24
ANGRY_SHORT_ANIMATION_ID = 34

FUSE_ANIMATION_ID = 33
